import type { JlptPoint } from "./grammar-data.js";

/**
 * JLPT N5 grammar, in plain words. One entry per point: what it is, what it
 * does in one breath, one example. Same no-jargon voice as the course:
 * do-words, describing words, things — never "verbs conjugating".
 */
export const N5_POINTS: JlptPoint[] = [
  { t: "は", n: "the “as for” flag", e: "Points at what we're talking about. The doer may hide behind it.", ex: "わたしは がくせいだ。", en: "As for me, (I) am a student." },
  { t: "が", n: "who's doing it", e: "Marks the one doing or being. Every sentence has one, even hidden.", ex: "ねこが ねる。", en: "The cat sleeps." },
  { t: "を", n: "what it's done to", e: "Marks the thing the doing lands on.", ex: "パンを たべる。", en: "(I) eat bread." },
  { t: "に", n: "the pin: to / at / on", e: "Pins a point: where it goes, where it sits, who it's aimed at, when it happens. Times take に exactly when English needs on/in/at (かようびに); words like today and tomorrow go bare.", ex: "がっこうに いく。", en: "(I) go to school." },
  { t: "で", n: "where or how", e: "The scene of the action, or the tool it's done with.", ex: "はしで たべる。", en: "(I) eat with chopsticks." },
  { t: "へ", n: "towards", e: "Points a direction — the journey, not the exact spot.", ex: "うちへ かえる。", en: "(I) head home." },
  { t: "と", n: "and / with", e: "Joins things into a complete list, or names who you did it with.", ex: "ともだちと はなす。", en: "(I) talk with a friend." },
  { t: "や", n: "and… among others", e: "Joins things into an open list — there's more you're not saying.", ex: "ペンや ほんを かう。", en: "(I) buy pens, books and such." },
  { t: "の", n: "belonging", e: "Ties two things together: A の B is A's B. It also files something under a group: ピンクいろの ドレス, “a dress of the pink kind”.", ex: "わたしの ほん。", en: "My book." },
  { t: "も", n: "too", e: "Swaps in for は or が to say “this one as well”.", ex: "わたしも いく。", en: "I'll go too." },
  { t: "から", n: "from", e: "Where or when something starts.", ex: "えきから あるく。", en: "(I) walk from the station." },
  { t: "まで", n: "until / as far as", e: "How far something goes, in place or time.", ex: "よるまで はたらく。", en: "(I) work until night." },
  { t: "までに", n: "by (a deadline)", e: "The latest moment something happens — done before then.", ex: "5じまでに かえる。", en: "(I'll) be home by five." },
  { t: "より", n: "than", e: "The thing being compared against.", ex: "いぬは ねこより おおきい。", en: "Dogs are bigger than cats." },
  { t: "か", n: "the spoken question mark", e: "Put it at the end and the sentence becomes a question.", ex: "いきますか。", en: "Are you going?" },
  { t: "ね", n: "right?", e: "Invites agreement — you feel the listener nodding.", ex: "いい てんきだね。", en: "Nice weather, right?" },
  { t: "よ", n: "you know", e: "Marks news — you're telling them something they didn't know.", ex: "おいしいよ。", en: "It's tasty, you know." },
  { t: "〜う (plain form)", n: "does / will do", e: "The dictionary form of a do-word. It points at the future more often than the present: いぬが たべる is usually “the dog will eat”. For happening-right-now, use 〜ている.", ex: "あした ケーキを たべる。", en: "Tomorrow (I'll) eat cake." },
  { t: "〜て", n: "the connector shape", e: "The linking form of a do-word: it hooks things on (〜ている, 〜てください) and chains actions — “do A and then B”. Made the same way as the 〜た past.", ex: "たべて、ねる。", en: "(I'll) eat and then sleep." },
  { t: "だ / です", n: "is", e: "Turns a thing into an ending: A だ means “(it) is A”. です is the polite twin.", ex: "これは ほんです。", en: "This is a book." },
  { t: "じゃない", n: "isn't", e: "The “is not” of だ: では (its connector shape) squeezed to じゃ, plus ない. Politely, じゃありません.", ex: "がくせいじゃない。", en: "(I'm) not a student." },
  { t: "〜ます", n: "polite doing", e: "The polite ending for do-words.", ex: "まいにち はしります。", en: "(I) run every day." },
  { t: "〜ました", n: "polite did", e: "The polite past: it already happened.", ex: "きのう みました。", en: "(I) watched it yesterday." },
  { t: "〜ません", n: "polite doesn't", e: "The polite “not doing”.", ex: "にくを たべません。", en: "(I) don't eat meat." },
  { t: "〜ませんでした", n: "polite didn't", e: "The polite “didn't do”.", ex: "いきませんでした。", en: "(I) didn't go." },
  { t: "〜ない", n: "plain not", e: "The everyday “not”: たべる → たべない. ない itself works like an い describing word — not-doing is a state, not an action — so it bends like one: たべなかった.", ex: "けさは たべない。", en: "(I'm) not eating this morning." },
  { t: "〜た", n: "did", e: "The everyday past: たべる → たべた.", ex: "もう たべた。", en: "(I) already ate." },
  { t: "〜ている", n: "is doing / is that way", e: "Literally “be doing”: the connector 〜て plus いる (be). Something happening right now, or a state that's settled in: しっている, “know”.", ex: "あめが ふっている。", en: "It's raining." },
  { t: "〜てください", n: "please do", e: "A polite request.", ex: "まって ください。", en: "Please wait." },
  { t: "〜ないでください", n: "please don't", e: "A polite “don't”.", ex: "わすれないで ください。", en: "Please don't forget." },
  { t: "〜てもいい", n: "it's okay to", e: "Gives or asks permission.", ex: "ここに すわってもいい？", en: "Can I sit here?" },
  { t: "〜てはいけない", n: "you can't do that", e: "Forbids something.", ex: "ここで およいでは いけない。", en: "You can't swim here." },
  { t: "〜たい", n: "want to", e: "Sticks onto a do-word: たべたい, “want to eat”. It then works like a describing word.", ex: "にほんへ いきたい。", en: "(I) want to go to Japan." },
  { t: "〜たことがある", n: "have done before", e: "Talks about an experience you have (or don't have).", ex: "すしを たべたことが ある。", en: "(I've) eaten sushi before." },
  { t: "〜たり〜たり", n: "things like A and B", e: "A loose sample of what happened — not the whole list, not in order.", ex: "よんだり ねたり する。", en: "(I) read, sleep, that sort of thing." },
  { t: "〜ながら", n: "while doing", e: "Two things at once; the main one comes last.", ex: "うたいながら あるく。", en: "(I) walk while singing." },
  { t: "〜まえに", n: "before doing", e: "What happens first goes after まえに.", ex: "ねるまえに はを みがく。", en: "(I) brush my teeth before bed." },
  { t: "〜てから", n: "after doing, then", e: "One thing, then the next — in that order.", ex: "たべてから でかける。", en: "(I'll) head out after eating." },
  { t: "〜たあとで", n: "after having done", e: "Once the first thing is done, the second happens.", ex: "しごとの あとで あそぶ。", en: "(I) have fun after work." },
  { t: "〜とき", n: "when", e: "“At the time of”: put the scene before とき.", ex: "ひまな とき、 ほんを よむ。", en: "When (I'm) free, (I) read." },
  { t: "〜ましょう", n: "let's", e: "Suggests doing it together.", ex: "いきましょう。", en: "Let's go." },
  { t: "〜ませんか", n: "won't you…?", e: "A gentle invitation.", ex: "いっしょに たべませんか。", en: "Won't you eat with me?" },
  { t: "〜ましょうか", n: "shall I?", e: "Offers to do something for someone.", ex: "てつだいましょうか。", en: "Shall I help?" },
  { t: "あまり〜ない", n: "not much", e: "With a “not” ending: only a little.", ex: "あまり たべない。", en: "(I) don't eat much." },
  { t: "ぜんぜん〜ない", n: "not at all", e: "With a “not” ending: zero.", ex: "ぜんぜん わからない。", en: "(I) don't get it at all." },
  { t: "ある / いる", n: "there is", e: "ある for things, いる for people and animals.", ex: "ねこが いる。つくえが ある。", en: "There's a cat. There's a desk." },
  { t: "〜がほしい", n: "want (a thing)", e: "For wanting things, not actions. The wanted thing wears が.", ex: "じかんが ほしい。", en: "(I) want time." },
  { t: "〜くらい / ぐらい", n: "about (an amount)", e: "A rough amount or extent.", ex: "10ぷんぐらい かかる。", en: "It takes about ten minutes." },
  { t: "〜ごろ", n: "around (a time)", e: "A rough point in time.", ex: "3じごろ つく。", en: "(I'll) arrive around three." },
  { t: "〜すぎる", n: "too much", e: "Sticks onto do-words and describing words: over the line.", ex: "たべすぎた。", en: "(I) ate too much." },
  { t: "だけ", n: "only", e: "Just this, nothing more.", ex: "みずだけ のむ。", en: "(I) drink only water." },
  { t: "〜でしょう", n: "probably", e: "A guess — or, with a rising voice, “right?”.", ex: "あしたは あめでしょう。", en: "It'll probably rain tomorrow." },
  { t: "〜という", n: "called", e: "Names something: “the thing called X”.", ex: "さくらという ねこ。", en: "A cat called Sakura." },
  { t: "〜にいく", n: "go to do", e: "The doing you're going for sits before に.", ex: "えいがを みに いく。", en: "(I'm) going to see a movie." },
  { t: "〜になる / 〜くなる", n: "become", e: "Change into something: things and な-words take になる, い-words drop い for くなる.", ex: "さむくなった。", en: "It got cold." },
  { t: "〜のがすき", n: "like doing", e: "の wraps the doing into a thing you can like.", ex: "およぐのが すきだ。", en: "(I) like swimming." },
  { t: "〜のがじょうず", n: "good at doing", e: "Same wrap, for skill.", ex: "うたうのが じょうずだ。", en: "(You're) good at singing." },
  { t: "〜のがへた", n: "bad at doing", e: "Same wrap, for the opposite.", ex: "りょうりを するのが へただ。", en: "(I'm) bad at cooking." },
  { t: "〜んです", n: "the explaining ending", e: "Wraps the sentence as background or reason — “the thing is…”.", ex: "あたまが いたいんです。", en: "The thing is, my head hurts." },
  { t: "まだ", n: "still / not yet", e: "Still going — or, with “not”, hasn't happened yet.", ex: "まだ たべていない。", en: "(I) haven't eaten yet." },
  { t: "もう", n: "already / anymore", e: "Already done — or, with “not”, no more.", ex: "もう おわった。", en: "It's already finished." },
  { t: "いちばん", n: "the most", e: "Number one of a group.", ex: "これが いちばん おいしい。", en: "This is the tastiest." },
  { t: "〜かた", n: "how to", e: "Sticks onto a do-word's stem: つかいかた, “how to use”.", ex: "かんじの よみかたが わからない。", en: "(I) don't know how to read this kanji." },
  { t: "〜をください", n: "please give me", e: "For asking for things.", ex: "みずを ください。", en: "Water, please." },
  { t: "〜けど / 〜が", n: "but (soft)", e: "Joins two halves that pull different ways; also softens a request.", ex: "たかいけど、かう。", en: "It's expensive, but (I'll) buy it." },
  { t: "でも", n: "but", e: "Starts a sentence that pushes back on the last one.", ex: "でも、いきたい。", en: "But (I) want to go." },
  { t: "だから", n: "so", e: "Starts the consequence.", ex: "あめだ。だから いかない。", en: "It's raining. So (I'm) not going." },
  { t: "それから", n: "and then", e: "The next thing in line.", ex: "たべた。それから ねた。", en: "(I) ate. And then slept." },
  { t: "しかし", n: "however", e: "The formal “but”.", ex: "しかし、もんだいが ある。", en: "However, there's a problem." },
  { t: "〜と〜と、どちら", n: "which of the two?", e: "Asks to pick between exactly two.", ex: "いぬと ねこと、どちらが すき？", en: "Dogs or cats — which do you like?" },
  { t: "〜のなかで〜がいちばん", n: "the best of the bunch", e: "Picks the top one out of a group.", ex: "くだものの なかで りんごが いちばん すきだ。", en: "Of all fruit, (I) like apples best." },
  { t: "なにか / なにも", n: "something / nothing", e: "なにか with a plain ending; なにも teams up with “not”.", ex: "なにも たべなかった。", en: "(I) ate nothing." },
  { t: "どうやって", n: "how?", e: "Asks the way something is done.", ex: "どうやって いくの？", en: "How do (we) get there?" },
];
