import type { JlptPoint } from "./grammar-data.js";

/** JLPT N3 grammar, in plain words. */
export const N3_POINTS: JlptPoint[] = [
  { t: "〜ばかり", n: "nothing but", e: "Doing or being one thing all the time.", ex: "ゲームばかり している。", en: "(He) does nothing but game." },
  { t: "〜たばかりに", n: "just because (regret)", e: "One small thing caused the whole mess.", ex: "急いだばかりに、転んだ。", en: "Just because (I) rushed, (I) fell." },
  { t: "〜うちに", n: "while it lasts", e: "Do it before the window closes.", ex: "熱いうちに 食べて。", en: "Eat it while it's hot." },
  { t: "〜あいだに", n: "at some point during", e: "Inside the stretch, something happened.", ex: "夜の あいだに 雪が つもった。", en: "Snow piled up during the night." },
  { t: "〜おかげで", n: "thanks to", e: "The cause you're grateful for.", ex: "先生の おかげで 合格した。", en: "Thanks to the teacher, (I) passed." },
  { t: "〜せいで", n: "because of (blame)", e: "The cause you're blaming.", ex: "雨の せいで 中止に なった。", en: "It was called off because of rain." },
  { t: "〜によって", n: "by / depending on", e: "The one behind it, the means, or “varies with”.", ex: "人に よって 好みが ちがう。", en: "Tastes differ from person to person." },
  { t: "〜にとって", n: "for (someone)", e: "Seen from that person's side.", ex: "わたしに とって 大切な 日だ。", en: "For me, it's an important day." },
  { t: "〜に対して", n: "towards", e: "Where an attitude or action is aimed; also “whereas”.", ex: "客に 対して ていねいに 話す。", en: "(We) speak politely to customers." },
  { t: "〜について", n: "about", e: "The subject under discussion.", ex: "日本の 歴史に ついて 話す。", en: "(We'll) talk about Japanese history." },
  { t: "〜に関して", n: "regarding", e: "The formal “about”.", ex: "この 件に 関して 質問は？", en: "Any questions regarding this matter?" },
  { t: "〜として", n: "as (a role)", e: "In the capacity of.", ex: "医者として 働いている。", en: "(She) works as a doctor." },
  { t: "〜とともに", n: "together with / as", e: "Along with something; or two changes moving together.", ex: "年を とるとともに、目が 弱くなる。", en: "As (you) age, the eyes weaken." },
  { t: "〜(よ)うとする", n: "try to / about to", e: "Pushing at the doing, or right on its edge.", ex: "出ようとしたら、雨が ふってきた。", en: "Just as (I) tried to leave, it started raining." },
  { t: "〜ことがある", n: "sometimes happens", e: "With a plain do-word: it happens now and then.", ex: "朝ごはんを 食べないことが ある。", en: "Sometimes (I) skip breakfast." },
  { t: "〜わけだ", n: "no wonder", e: "The pieces click: so that's why.", ex: "寒いわけだ。雪が ふっている。", en: "No wonder it's cold — it's snowing." },
  { t: "〜わけではない", n: "it's not that", e: "Blocks the obvious reading: not exactly.", ex: "きらいな わけではない。", en: "It's not that (I) dislike it." },
  { t: "〜わけがない", n: "no way", e: "Flat impossible, as you see it.", ex: "そんなこと、できるわけがない。", en: "There's no way (I) could do that." },
  { t: "〜わけにはいかない", n: "can't afford to", e: "Possible in theory — but duty or sense forbids it.", ex: "休むわけにはいかない。", en: "(I) can't afford to take a day off." },
  { t: "〜くせに", n: "even though (accusing)", e: "のに with a glare.", ex: "知っているくせに、教えない。", en: "(You) know, yet (you) won't tell." },
  { t: "〜ば〜ほど", n: "the more, the more", e: "More of A means more of B.", ex: "読めば 読むほど おもしろい。", en: "The more (I) read, the better it gets." },
  { t: "〜ほど", n: "so much that", e: "The extent, painted with a picture.", ex: "泣くほど うれしかった。", en: "(I) was happy enough to cry." },
  { t: "〜くらい〜はない", n: "nothing as … as", e: "Puts it at the very top.", ex: "今日くらい 暑い日は ない。", en: "No day is as hot as today." },
  { t: "〜に違いない", n: "must be", e: "You're all but certain.", ex: "あの 人が 犯人に 違いない。", en: "That person must be the culprit." },
  { t: "〜っぽい", n: "-ish", e: "Has that flavour: 子どもっぽい, “childish”.", ex: "この 服は 安っぽい。", en: "These clothes look cheap." },
  { t: "〜がち", n: "tends to", e: "Happens more often than you'd like.", ex: "冬は かぜを ひきがちだ。", en: "In winter (I) tend to catch colds." },
  { t: "〜気味", n: "a touch of", e: "A slight lean that way: つかれ気味, “a bit worn out”.", ex: "かぜ気味で 早く 帰った。", en: "Feeling a cold coming on, (I) left early." },
  { t: "〜かけ", n: "half-done", e: "Started and abandoned mid-way: 食べかけ, “half-eaten”.", ex: "読みかけの 本が ある。", en: "There's a book (I'm) partway through." },
  { t: "〜きる", n: "do completely", e: "All the way to the end: 使いきる, “use up”.", ex: "マラソンを 走りきった。", en: "(I) ran the whole marathon." },
  { t: "〜きれない", n: "can't finish", e: "Too much to get through.", ex: "多すぎて 食べきれない。", en: "It's too much to eat up." },
  { t: "〜っぱなし", n: "left running", e: "Done and never undone — usually careless.", ex: "水を 出しっぱなしに した。", en: "(I) left the water running." },
  { t: "〜たび（に）", n: "every time", e: "Each occurrence brings the same thing.", ex: "会うたびに 元気を もらう。", en: "Every time (we) meet, (I'm) cheered up." },
  { t: "〜最中に", n: "right in the middle of", e: "At the very peak of doing it — often interrupted.", ex: "会議の 最中に 電話が 鳴った。", en: "The phone rang mid-meeting." },
  { t: "〜たとたん", n: "the instant", e: "A happened, and B was already there.", ex: "ドアを 開けたとたん、猫が 出た。", en: "The instant (I) opened the door, the cat shot out." },
  { t: "〜ことにしている", n: "make it a rule", e: "A standing decision you keep.", ex: "夜は 食べないことにしている。", en: "(I) make it a rule not to eat at night." },
  { t: "〜ことになっている", n: "it's the rule", e: "Fixed by rule, custom or schedule.", ex: "ここでは くつを ぬぐことになっている。", en: "The rule here is shoes off." },
  { t: "〜こそ", n: "this and nothing else", e: "Spotlights the word before it.", ex: "今年こそ 合格する。", en: "This year for sure, (I'll) pass." },
  { t: "〜さえ", n: "even", e: "Even this — so everything else goes without saying.", ex: "ひらがなさえ 読めない。", en: "(He) can't even read hiragana." },
  { t: "〜さえ〜ば", n: "if only", e: "This one thing is all it takes.", ex: "時間さえ あれば できる。", en: "Given just time, (I) can do it." },
  { t: "〜でも", n: "even / or something", e: "Even that one; or a soft example: お茶でも.", ex: "子どもでも わかる。", en: "Even a child gets it." },
  { t: "〜のではないか", n: "isn't it that…?", e: "Floats your hunch as a question.", ex: "まちがいなのではないか。", en: "Isn't this a mistake?" },
  { t: "〜って", n: "casual quote", e: "The spoken と / という: what someone said or a thing's name.", ex: "行くって 言ってた。", en: "(He) said he's going." },
  { t: "〜とか", n: "things like", e: "A loose list, or a hazy report.", ex: "映画とか 音楽が 好きだ。", en: "(I) like movies, music, that kind of thing." },
  { t: "〜なんか / なんて", n: "something like (dismissive)", e: "Waves the thing down — often scorn or modesty.", ex: "うそなんか つかない。", en: "(I) don't tell lies or anything like that." },
  { t: "〜ずつ", n: "each / at a time", e: "Even shares or steady steps.", ex: "少しずつ よくなる。", en: "It gets better little by little." },
  { t: "〜だらけ", n: "covered in", e: "Full of something unwelcome.", ex: "どろだらけに なった。", en: "(I) got covered in mud." },
  { t: "〜だけでなく", n: "not only", e: "Not only A — B too.", ex: "英語だけでなく 中国語も 話す。", en: "(She) speaks not only English but Chinese." },
  { t: "〜ばかりでなく", n: "not just", e: "The formal “not only… but also”.", ex: "味ばかりでなく 見た目も いい。", en: "Not just the taste — it looks good too." },
  { t: "〜みたいに", n: "like (comparison)", e: "Paints one thing with another's colours.", ex: "鳥みたいに 飛びたい。", en: "(I) want to fly like a bird." },
  { t: "〜ように言う", n: "tell someone to", e: "Passes an instruction along.", ex: "待つように 言われた。", en: "(I) was told to wait." },
  { t: "〜ため、", n: "owing to", e: "The written-style cause.", ex: "事故の ため、遅れています。", en: "Owing to an accident, (we're) delayed." },
  { t: "〜は〜で有名", n: "famous for", e: "What a place or person is known by.", ex: "京都は 寺で 有名だ。", en: "Kyoto is famous for its temples." },
  { t: "〜という意味", n: "means…", e: "Unpacks what a word or sign says.", ex: "これは 「止まれ」という 意味だ。", en: "This means “stop”." },
  { t: "〜ながらも", n: "while yet", e: "Both are true, and they pull against each other.", ex: "せまいながらも、いい 部屋だ。", en: "Small as it is, it's a good room." },
  { t: "〜おかげか", n: "perhaps thanks to", e: "The happy cause, hedged.", ex: "薬の おかげか、楽に なった。", en: "Maybe thanks to the medicine, (I) feel better." },
  { t: "〜に比べて", n: "compared with", e: "Sets the measuring stick.", ex: "去年に 比べて 暑い。", en: "It's hot compared with last year." },
  { t: "〜にしたがって", n: "as (one changes, so does)", e: "B keeps pace with A.", ex: "上がるにしたがって 寒くなる。", en: "As (you) climb, it gets colder." },
  { t: "〜につれて", n: "as… goes on", e: "Change riding along with change.", ex: "時間が たつにつれて 慣れた。", en: "As time passed, (I) got used to it." },
  { t: "〜ほど〜ない", n: "not as… as", e: "Falls short of the comparison.", ex: "今日は 昨日ほど 寒くない。", en: "Today isn't as cold as yesterday." },
  { t: "〜かわりに", n: "instead / in exchange", e: "One thing stands in for another, or balances it.", ex: "母の かわりに 来た。", en: "(I) came in my mother's place." },
  { t: "〜てばかりいる", n: "does nothing but", e: "The same doing, over and over — said with a frown.", ex: "泣いてばかりいる。", en: "(She) does nothing but cry." },
  { t: "〜はもちろん", n: "not to mention", e: "A is a given — and B besides.", ex: "平日は もちろん、週末も 働く。", en: "Weekdays of course — weekends too." },
  { t: "〜べきだ", n: "ought to", e: "What's right to do, by your lights.", ex: "あやまるべきだ。", en: "(You) ought to apologize." },
  { t: "〜べきではない", n: "ought not to", e: "The wrong thing to do.", ex: "言うべきではなかった。", en: "(I) shouldn't have said it." },
  { t: "〜ようとしない", n: "won't even try", e: "Refuses to push at the doing at all.", ex: "話を 聞こうとしない。", en: "(He) won't even try to listen." },
  { t: "〜がる (N3 use)", n: "acts like it feels", e: "Feelings shown from outside, for describing others.", ex: "むずかしがらないで。", en: "Don't act like it's too hard." },
  { t: "お〜ください", n: "please (formal)", e: "The extra-polite request shape.", ex: "こちらで お待ちください。", en: "Please wait here." },
  { t: "〜てほしくない", n: "don't want someone to", e: "The doing you'd rather not receive.", ex: "来てほしくない。", en: "(I) don't want (him) to come." },
  { t: "〜間違いない", n: "no mistake", e: "Certainty, stamped.", ex: "これで 間違いない。", en: "This is it, no mistake." },
];
