import type { JlptPoint } from "./grammar-data.js";

/** JLPT N4 grammar, in plain words. */
export const N4_POINTS: JlptPoint[] = [
  { t: "でる / だす pairs", n: "moves itself vs moves something", e: "Japanese keeps two versions of a word: one where the thing moves by itself (でる, come out) and one where somebody moves it (だす, take out). ある is the parent of all self-movers, する of all the others.", ex: "でんしゃが でる。かばんを だす。", en: "The train leaves. (I) take out the bag." },
  { t: "には / にも / とは", n: "a flag on top of a car", e: "に, で and と keep their job and take は or も on top: には, にも, とは. が and を never stack like this — they just step aside.", ex: "ここには なにも ない。", en: "As for here, there's nothing." },
  { t: "sentence + thing", n: "a sentence as a describer", e: "Park a whole plain sentence in front of a thing and it describes it: うたった しょうじょ, “the girl who sang”. Japanese does this constantly, where English needs “who” or “that”.", ex: "じしょを たべた いぬが ねている。", en: "The dog that ate the dictionary is sleeping." },
  { t: "〜たら", n: "if / when", e: "The everyday “if”: once A happens, B. Works for one-off “when” too.", ex: "あめが ふったら、うちに いる。", en: "If it rains, (I'll) stay home." },
  { t: "〜ば", n: "if", e: "The tidy “if”: A ば B — B holds whenever A does.", ex: "やすければ かう。", en: "If it's cheap, (I'll) buy it." },
  { t: "〜なら", n: "if that's the case", e: "Takes what was just said and builds on it.", ex: "いくなら、いっしょに いこう。", en: "If you're going, let's go together." },
  { t: "〜と (whenever)", n: "whenever A, B", e: "A leads to B every time — like a law of nature.", ex: "はるに なると、はなが さく。", en: "When spring comes, flowers bloom." },
  { t: "〜てしまう", n: "completely / oh no", e: "Finished for good — or it happened and you wish it hadn't.", ex: "ぜんぶ たべてしまった。", en: "(I) ate it all." },
  { t: "〜ちゃう", n: "casual てしまう", e: "The everyday spoken squeeze of てしまう.", ex: "わすれちゃった。", en: "(I) went and forgot." },
  { t: "〜ておく", n: "do it ahead", e: "Do it now so things are ready later.", ex: "きっぷを かっておく。", en: "(I'll) buy the tickets in advance." },
  { t: "〜てみる", n: "try doing", e: "Give it a go and see.", ex: "きてみて。", en: "Try it on." },
  { t: "〜てあげる", n: "do for someone", e: "You do it as a favour, outward.", ex: "てつだって あげる。", en: "(I'll) help you." },
  { t: "〜てくれる", n: "someone does for me", e: "The favour flows your way.", ex: "ともだちが おしえてくれた。", en: "A friend taught me." },
  { t: "〜てもらう", n: "get someone to do", e: "You receive the doing — often you asked for it.", ex: "みちを おしえてもらった。", en: "(I) got directions." },
  { t: "〜てある", n: "done and left that way", e: "Someone did it on purpose, and the result is still sitting there.", ex: "まどが あけてある。", en: "The window's been left open." },
  { t: "〜ているところ", n: "in the middle of", e: "Caught mid-action.", ex: "いま たべているところだ。", en: "(I'm) in the middle of eating." },
  { t: "〜るところ", n: "about to", e: "On the very edge of starting.", ex: "でかけるところだ。", en: "(I'm) just about to leave." },
  { t: "〜たところ", n: "just did", e: "Fresh off finishing.", ex: "いま ついたところだ。", en: "(I) just arrived." },
  { t: "〜たばかり", n: "only just did", e: "So recent it still colours things.", ex: "はじめたばかりだ。", en: "(I've) only just started." },
  { t: "〜られる (can)", n: "can do", e: "Morphs a do-word into “able to do it”: たべる → たべられる.", ex: "なっとうが たべられる。", en: "(I) can eat natto." },
  { t: "〜られる (happens to you)", n: "it lands on you", e: "The doing comes at you from someone else — often unasked. Not a backwards sentence: the one it lands on is still the doer of the receiving, so あめに ふられた is “(I) received the rain's falling”.", ex: "あめに ふられた。", en: "(I) got rained on." },
  { t: "〜させる", n: "make or let someone do", e: "You cause the doing: force it or allow it.", ex: "こどもに やさいを たべさせる。", en: "(I) make the kids eat vegetables." },
  { t: "〜させられる", n: "be made to do", e: "Someone causes it, and it lands on you.", ex: "またされた? いえ、うたわせられた。", en: "(I) was made to sing." },
  { t: "〜そうだ (looks)", n: "looks about to", e: "From what you see: it looks that way, or about to happen.", ex: "あめが ふりそうだ。", en: "It looks like rain." },
  { t: "〜そうだ (heard)", n: "I hear that", e: "Passing on what you heard, as heard.", ex: "あした あめが ふるそうだ。", en: "They say it'll rain tomorrow." },
  { t: "〜ようだ", n: "it seems", e: "Your read of the signs.", ex: "だれも いないようだ。", en: "It seems nobody's here." },
  { t: "〜みたい", n: "seems / like", e: "The everyday ようだ; also “like” for comparisons.", ex: "ゆめみたいだ。", en: "It's like a dream." },
  { t: "〜らしい", n: "apparently", e: "Second-hand but believed; also “true to type”: おとこらしい.", ex: "てんきんに なるらしい。", en: "Apparently (he's) being transferred." },
  { t: "〜かもしれない", n: "might", e: "Maybe — you're not sure either way.", ex: "おくれるかもしれない。", en: "(I) might be late." },
  { t: "〜はずだ", n: "should be", e: "By everything you know, this follows.", ex: "もう ついたはずだ。", en: "(They) should have arrived by now." },
  { t: "〜はずがない", n: "can't possibly be", e: "By everything you know, this can't hold.", ex: "そんな はずが ない。", en: "That can't be." },
  { t: "〜だろう", n: "probably (plain)", e: "The plain twin of でしょう.", ex: "だいじょうぶだろう。", en: "It's probably fine." },
  { t: "〜と思う", n: "I think", e: "Marks the sentence as your opinion.", ex: "いいと おもう。", en: "(I) think it's good." },
  { t: "〜と言っていた", n: "said that", e: "Reports someone's words.", ex: "くると いっていた。", en: "(She) said she's coming." },
  { t: "〜か (folded question)", n: "a question inside", e: "Folds a question into a bigger sentence.", ex: "どこに あるか わからない。", en: "(I) don't know where it is." },
  { t: "〜かどうか", n: "whether or not", e: "Folds in a yes-or-no question.", ex: "いくかどうか きめていない。", en: "(I) haven't decided whether to go." },
  { t: "〜なさい", n: "do it (parent-style)", e: "A firm order from above — parents, teachers.", ex: "はやく ねなさい。", en: "Go to bed." },
  { t: "〜ないで", n: "without doing", e: "Skip A and do B; also a plain “don't”.", ex: "あさごはんを たべないで きた。", en: "(I) came without breakfast." },
  { t: "〜ずに", n: "without doing (written)", e: "The bookish ないで.", ex: "なにも いわずに でた。", en: "(He) left without a word." },
  { t: "〜なくてもいい", n: "don't have to", e: "Skipping it is fine.", ex: "こなくてもいい。", en: "You don't have to come." },
  { t: "〜なければならない", n: "have to", e: "No way around it.", ex: "もう いかなければならない。", en: "(I) have to go now." },
  { t: "〜なくちゃ / なきゃ", n: "gotta", e: "The spoken squeeze of “have to”.", ex: "べんきょうしなきゃ。", en: "Gotta study." },
  { t: "〜たほうがいい", n: "you'd better", e: "Advice: this is the better path.", ex: "やすんだほうがいい。", en: "You'd better rest." },
  { t: "〜ないほうがいい", n: "better not", e: "Advice against.", ex: "いわないほうがいい。", en: "Better not say it." },
  { t: "〜やすい", n: "easy to", e: "Sticks onto the stem: よみやすい, “easy to read”.", ex: "この ペンは かきやすい。", en: "This pen is easy to write with." },
  { t: "〜にくい", n: "hard to", e: "The opposite of やすい.", ex: "この かんじは おぼえにくい。", en: "This kanji is hard to remember." },
  { t: "〜さ", n: "-ness", e: "Turns a describing word into a measurable thing: たかさ, “height”.", ex: "うみの ふかさを はかる。", en: "Measure the sea's depth." },
  { t: "〜がる", n: "shows someone's feeling", e: "You can't feel others' feelings — がる says they're showing it.", ex: "いもうとは こわがっている。", en: "My sister is acting scared." },
  { t: "〜たがる", n: "someone wants to", e: "たい for other people, seen from outside.", ex: "むすこは そとで あそびたがる。", en: "My son wants to play outside." },
  { t: "お〜になる", n: "respectful doing", e: "Raises the other person's action politely.", ex: "せんせいが おかきになった。", en: "The teacher wrote it." },
  { t: "お〜する", n: "humble doing", e: "Lowers your own action politely.", ex: "おもちします。", en: "(I'll) carry it for you." },
  { t: "〜てくださいませんか", n: "would you please", e: "An extra-polite request.", ex: "みて くださいませんか。", en: "Would you please take a look?" },
  { t: "〜させてください", n: "please let me", e: "Asks permission to do it yourself.", ex: "やらせてください。", en: "Please let me do it." },
  { t: "〜ように", n: "so that", e: "The aim comes first, the effort after.", ex: "きこえるように おおきく はなす。", en: "(I) speak up so (I'm) heard." },
  { t: "〜ようにする", n: "make a point of", e: "A habit you keep on purpose.", ex: "まいにち あるくようにしている。", en: "(I) make a point of walking daily." },
  { t: "〜ようになる", n: "come to", e: "A change that arrived over time.", ex: "およげるようになった。", en: "(I) came to be able to swim." },
  { t: "〜ことにする", n: "decide to", e: "Your own decision.", ex: "いくことにした。", en: "(I) decided to go." },
  { t: "〜ことになる", n: "it's been decided", e: "The decision came from elsewhere.", ex: "てんきんすることになった。", en: "It's been decided (I'm) transferring." },
  { t: "〜ことができる", n: "can (formal)", e: "The roundabout, formal “can do”.", ex: "ここで かりることができる。", en: "You can borrow (them) here." },
  { t: "〜ため（に）", n: "for / because of", e: "A purpose — or a cause, when it explains a result.", ex: "かぞくの ために はたらく。", en: "(I) work for my family." },
  { t: "〜のに", n: "even though", e: "Reality went against expectation — often with a sigh.", ex: "べんきょうしたのに、おちた。", en: "Even though (I) studied, (I) failed." },
  { t: "〜ので", n: "because (soft)", e: "A gentle reason — softer than から.", ex: "さむいので、しめます。", en: "It's cold, so (I'll) close it." },
  { t: "〜し", n: "and what's more", e: "Stacks reasons.", ex: "やすいし、おいしいし。", en: "It's cheap, and it's good." },
  { t: "〜まま", n: "leaving it as is", e: "The state stays put while something else happens.", ex: "でんきを つけたまま ねた。", en: "(I) slept with the light on." },
  { t: "〜つもり", n: "plan to", e: "Your intention.", ex: "らいねん いくつもりだ。", en: "(I) plan to go next year." },
  { t: "〜よてい", n: "scheduled to", e: "It's on the schedule.", ex: "3じに つくよていだ。", en: "(It's) due to arrive at three." },
  { t: "〜だす", n: "burst into doing", e: "It starts suddenly: なきだす, “burst into tears”.", ex: "あめが ふりだした。", en: "It started to rain." },
  { t: "〜はじめる", n: "start doing", e: "The plain start of an action.", ex: "ほんを よみはじめた。", en: "(I) started reading the book." },
  { t: "〜おわる", n: "finish doing", e: "The action's end.", ex: "よみおわった。", en: "(I) finished reading." },
  { t: "〜つづける", n: "keep doing", e: "The action carries on.", ex: "はしりつづけた。", en: "(I) kept running." },
  { t: "〜がする", n: "I sense…", e: "A smell, sound, taste or feeling reaches you.", ex: "いい においが する。", en: "Something smells good." },
  { t: "〜てほしい", n: "want someone to", e: "You want the doing done by someone else.", ex: "きいてほしい。", en: "(I) want you to listen." },
  { t: "〜ばあいは", n: "in case of", e: "Sets up a scenario and what to do in it.", ex: "おくれるばあいは、でんわして。", en: "If (you'll) be late, call." },
  { t: "〜あいだ（に）", n: "while / during", e: "あいだ spans the whole stretch; あいだに means at some point inside it.", ex: "るすの あいだに きた。", en: "(He) came while (I) was out." },
  { t: "〜ても", n: "even if", e: "It makes no difference to what follows.", ex: "あめでも いく。", en: "Even if it rains, (I'll) go." },
  { t: "〜ていく / 〜てくる", n: "going on / coming to be", e: "Change moving away from now, or arriving up to now.", ex: "さむくなってきた。", en: "It's been getting cold." },
  { t: "〜（よ）う", n: "let's / I'll (plain)", e: "The plain push of ましょう: いこう, “let's go”.", ex: "そろそろ かえろう。", en: "Let's head home." },
  { t: "〜（よ）うと思う", n: "I think I'll", e: "A plan forming: your push plus と思う.", ex: "やめようと おもう。", en: "(I) think I'll quit." },
];
