import type { JlptPoint } from "./grammar-data.js";

/** JLPT N2 grammar, in plain words. */
export const N2_POINTS: JlptPoint[] = [
  { t: "〜わりに", n: "considering", e: "More or less than you'd expect from the given fact.", ex: "値段の わりに おいしい。", en: "For the price, it's good." },
  { t: "〜あげく", n: "after all that", e: "A long struggle, ending badly.", ex: "迷った あげく、やめた。", en: "After all that dithering, (I) gave up." },
  { t: "〜末に", n: "at the end of", e: "A long process, and where it landed.", ex: "話し合いの 末に 決めた。", en: "(We) decided after long discussion." },
  { t: "〜たところ", n: "when I did, I found", e: "You did A, and this is what turned up.", ex: "聞いたところ、本当だった。", en: "When (I) asked, it turned out true." },
  { t: "〜次第", n: "as soon as", e: "The moment A lands, B follows.", ex: "着き次第、連絡します。", en: "(I'll) contact you the moment (I) arrive." },
  { t: "〜次第だ／で", n: "rides on", e: "The outcome hangs on that one thing.", ex: "君の 返事次第だ。", en: "It rides on your answer." },
  { t: "〜に応じて", n: "to match", e: "Adjusted to fit what's there.", ex: "予算に 応じて 選べる。", en: "(You) can choose to match your budget." },
  { t: "〜に基づいて", n: "based on", e: "Built on that foundation.", ex: "事実に 基づいて 書いた。", en: "Written based on the facts." },
  { t: "〜をもとに", n: "drawing on", e: "The raw material it grew from.", ex: "実話を もとに した映画。", en: "A film drawn from a true story." },
  { t: "〜をきっかけに", n: "sparked by", e: "The small event that set it off.", ex: "旅行を きっかけに 日本語を 始めた。", en: "A trip sparked (my) Japanese." },
  { t: "〜を通じて / を通して", n: "through", e: "By way of; or spanning the whole stretch.", ex: "友人を 通じて 知り合った。", en: "(We) met through a friend." },
  { t: "〜にわたって", n: "spanning", e: "Stretched across that whole range.", ex: "十年に わたって 続いた。", en: "It ran on for ten years." },
  { t: "〜に沿って", n: "along / in line with", e: "Following the line laid down.", ex: "計画に 沿って 進める。", en: "(We'll) proceed in line with the plan." },
  { t: "〜に反して", n: "contrary to", e: "The result crossed the expectation.", ex: "予想に 反して 勝った。", en: "Contrary to predictions, (they) won." },
  { t: "〜にもかかわらず", n: "despite", e: "The fact pushed one way; things went the other.", ex: "雨にも かかわらず 来てくれた。", en: "Despite the rain, (they) came." },
  { t: "〜のみならず", n: "not only (formal)", e: "The stiff, written “not only… but”.", ex: "国内のみならず 海外でも 人気だ。", en: "Popular not only at home but abroad." },
  { t: "〜ばかりか", n: "not just — even", e: "Beyond A, it reaches B.", ex: "熱ばかりか、せきも 出る。", en: "Not just a fever — a cough too." },
  { t: "〜どころか", n: "far from it", e: "Reality isn't just short of the claim — it's the reverse.", ex: "晴れるどころか、大雨だ。", en: "Far from clearing up, it's pouring." },
  { t: "〜どころではない", n: "no time for", e: "Circumstances rule it right out.", ex: "旅行どころではない。", en: "A trip is out of the question." },
  { t: "〜ものだ", n: "that's how it is", e: "The way of things; also warm looking-back: よく遊んだものだ.", ex: "時間は 早く たつものだ。", en: "Time just does fly." },
  { t: "〜ものの", n: "though", e: "A holds, but what should follow didn't.", ex: "買ったものの、使っていない。", en: "(I) bought it, but never use it." },
  { t: "〜というものだ", n: "that's precisely", e: "Names what the thing really amounts to.", ex: "それは わがままというものだ。", en: "That's what selfishness is." },
  { t: "〜というものではない", n: "doesn't mean that", e: "Blocks the sweeping conclusion.", ex: "安ければ いいというものではない。", en: "Cheap doesn't automatically mean good." },
  { t: "〜ことだ", n: "the thing to do is", e: "Direct advice, boiled to one line.", ex: "早く 寝ることだ。", en: "The thing to do is sleep early." },
  { t: "〜ことか", n: "how…!", e: "An exclamation of degree: how many times, how much.", ex: "何度 言ったことか。", en: "How many times have (I) said it!" },
  { t: "〜ことなく", n: "without ever", e: "The formal “without doing”.", ex: "休むことなく 働いた。", en: "(He) worked without ever resting." },
  { t: "〜ことに", n: "to my…", e: "Your reaction, put before the fact: 驚いたことに.", ex: "残念なことに、負けた。", en: "To (my) regret, (we) lost." },
  { t: "〜ざるを得ない", n: "have no choice but", e: "Pressed into it against your wishes.", ex: "認めざるを得ない。", en: "(I) have no choice but to admit it." },
  { t: "〜ずにはいられない", n: "can't help doing", e: "The urge wins every time.", ex: "笑わずには いられない。", en: "(I) can't help laughing." },
  { t: "〜ないわけにはいかない", n: "can't very well not", e: "Duty forbids skipping it.", ex: "行かないわけにはいかない。", en: "(I) can't very well not go." },
  { t: "〜かねる", n: "can't quite (politely)", e: "The soft business “unable to”.", ex: "お答えしかねます。", en: "(I'm) afraid (I) can't answer that." },
  { t: "〜かねない", n: "could well (badly)", e: "Quite capable of ending badly.", ex: "事故に なりかねない。", en: "It could well end in an accident." },
  { t: "〜がたい", n: "hard to (deeply)", e: "Almost beyond doing: 信じがたい, “hard to believe”.", ex: "忘れがたい 一日だった。", en: "A hard day to forget." },
  { t: "〜得る / 〜得ない", n: "possible / impossible", e: "Whether it can happen at all.", ex: "あり得ない 話だ。", en: "An impossible story." },
  { t: "〜おそれがある", n: "risk of", e: "The bad outcome is on the table.", ex: "津波の おそれが ある。", en: "There is a risk of tsunami." },
  { t: "〜まい", n: "surely not / I won't", e: "A written “probably not” — or your own firm refusal.", ex: "二度と 行くまい。", en: "(I'll) not go again." },
  { t: "〜つつ", n: "while (written)", e: "The bookish ながら; つつも adds “and yet”.", ex: "悪いと 知りつつ、やった。", en: "Knowing it was wrong, (I) did it." },
  { t: "〜つつある", n: "in the course of", e: "The change is underway right now.", ex: "町は 変わりつつある。", en: "The town is changing." },
  { t: "〜一方だ", n: "only ever (one direction)", e: "The change runs one way and keeps going.", ex: "物価は 上がる一方だ。", en: "Prices just keep rising." },
  { t: "〜一方で", n: "on the other hand", e: "Two sides of the same thing, held together.", ex: "厳しい 一方で、やさしい。", en: "Strict — and kind at the same time." },
  { t: "〜反面", n: "on the flip side", e: "The built-in downside (or upside).", ex: "便利な 反面、高い。", en: "Handy — but pricey, on the flip side." },
  { t: "〜げ", n: "with an air of", e: "The look of a feeling: さびしげ, “forlorn-looking”.", ex: "楽しげに 話す。", en: "(She) talks with a happy air." },
  { t: "〜だけあって", n: "as you'd expect from", e: "Lives up to its billing.", ex: "プロだけあって、うまい。", en: "A pro, and it shows." },
  { t: "〜だけに", n: "all the more because", e: "The fact turns the feeling up.", ex: "期待していただけに、残念だ。", en: "All the more disappointing for the hopes (I) had." },
  { t: "〜からこそ", n: "precisely because", e: "This reason and no other.", ex: "君だからこそ 頼む。", en: "(I'm) asking precisely because it's you." },
  { t: "〜からには", n: "now that", e: "Having come this far, see it through.", ex: "やるからには、勝ちたい。", en: "Now that (we're) doing it, (I) want to win." },
  { t: "〜からといって", n: "just because", e: "The reason doesn't license the conclusion.", ex: "若いからといって、無理は できない。", en: "Being young doesn't mean (you) can overdo it." },
  { t: "〜以上（は）", n: "seeing that", e: "The fact stands — so act accordingly.", ex: "約束した 以上、守る。", en: "Having promised, (I'll) keep it." },
  { t: "〜上で", n: "after / upon", e: "First A, and on top of it B; also “in the course of”.", ex: "確認の 上で、送ります。", en: "(I'll) send it after checking." },
  { t: "〜上に", n: "on top of", e: "One thing stacked on another, same direction.", ex: "安い 上に うまい。", en: "Cheap, and on top of that, good." },
  { t: "〜限り", n: "as long as", e: "While that holds, so does this.", ex: "生きている 限り、学ぶ。", en: "As long as (I) live, (I) learn." },
  { t: "〜に限って", n: "of all…", e: "Trust it to be this one; also “this one never would”.", ex: "急ぐ日に 限って 電車が 遅れる。", en: "Trains run late precisely when (you're) rushed." },
  { t: "〜に限らず", n: "not limited to", e: "It spills past that boundary.", ex: "子どもに 限らず 大人も 楽しめる。", en: "Not just kids — adults enjoy it too." },
  { t: "〜てたまらない", n: "unbearably", e: "The feeling is too strong to sit with.", ex: "会いたくて たまらない。", en: "(I) miss (you) unbearably." },
  { t: "〜てならない", n: "can't shake the feeling", e: "It wells up on its own.", ex: "気に なって ならない。", en: "(I) can't stop worrying about it." },
  { t: "〜てしょうがない", n: "no use — it just is", e: "The everyday “unbearably”.", ex: "眠くて しょうがない。", en: "(I'm) hopelessly sleepy." },
  { t: "〜ようがない", n: "no way to", e: "The means simply don't exist.", ex: "連絡先が なくて、知らせようがない。", en: "With no contact info, there's no way to tell (them)." },
  { t: "〜ことから", n: "from the fact that", e: "The clue the conclusion grew from.", ex: "足あとが あることから、くまだと わかった。", en: "From the tracks, (we) knew it was a bear." },
  { t: "〜ことだから", n: "knowing (them)", e: "Their character makes the guess safe.", ex: "彼の ことだから、遅れるだろう。", en: "Knowing him, (he'll) be late." },
  { t: "〜ぬきで / ぬきに", n: "leaving out", e: "With that part removed.", ex: "冗談ぬきで 話そう。", en: "Joking aside, let's talk." },
  { t: "〜を問わず", n: "no matter", e: "That difference doesn't matter here.", ex: "年齢を 問わず 参加できる。", en: "Anyone can join, whatever their age." },
  { t: "〜はともかく", n: "setting aside", e: "Park that question; move to the real one.", ex: "見た目は ともかく、味は いい。", en: "Looks aside, it tastes good." },
  { t: "〜といえば", n: "speaking of", e: "Picks up a word and runs with it.", ex: "京都といえば、紅葉だ。", en: "Speaking of Kyoto — autumn leaves." },
  { t: "〜とはいえ", n: "that said", e: "True — but not the whole story.", ex: "春とはいえ、まだ寒い。", en: "Spring, that said — still cold." },
  { t: "〜ながらの", n: "as it always was", e: "Kept the old way: 昔ながらの, “time-honoured”.", ex: "昔ながらの 店が 残る。", en: "Old-style shops remain." },
  { t: "〜っこない", n: "no chance", e: "The blunt spoken “never gonna happen”.", ex: "そんなの、できっこない。", en: "No chance (I) can do that." },
  { t: "〜ぶり", n: "for the first time in", e: "The gap since last time; also “the manner of”.", ex: "十年ぶりに 会った。", en: "(We) met for the first time in ten years." },
  { t: "〜がい", n: "worth doing", e: "The reward that makes the effort pay: やりがい.", ex: "教えがいの ある 学生だ。", en: "A student worth teaching." },
];

/** JLPT N1 grammar, in plain words. */
export const N1_POINTS: JlptPoint[] = [
  { t: "〜んばかりに", n: "as if about to", e: "So close to happening you can see it.", ex: "泣かんばかりに 頼んだ。", en: "(She) begged, all but in tears." },
  { t: "〜とばかりに", n: "as if to say", e: "The unspoken message, acted out.", ex: "帰れとばかりに ドアを 指した。", en: "(He) pointed at the door as if to say “leave”." },
  { t: "〜ものを", n: "if only (reproach)", e: "It could have gone well — and didn't.", ex: "言えば 助けたものを。", en: "If (you'd) only said — (I'd) have helped." },
  { t: "〜ものなら", n: "if (you dare / could)", e: "A doubtful or risky if: try it and see.", ex: "できるものなら、やってみろ。", en: "If (you) can, go ahead and try." },
  { t: "〜んがために", n: "for the sole sake of", e: "The old, heavy “in order to”.", ex: "勝たんがために 練習する。", en: "(They) train solely to win." },
  { t: "〜べく", n: "so as to (written)", e: "The stiff written “in order to”.", ex: "医者に なるべく 上京した。", en: "(He) moved to the capital to become a doctor." },
  { t: "〜べからず", n: "must not (sign-style)", e: "The carved-in-stone prohibition.", ex: "ここに 入るべからず。", en: "Do not enter." },
  { t: "〜まじき", n: "unbecoming of", e: "Conduct the role forbids: あるまじき行為.", ex: "教師に あるまじき 発言だ。", en: "A remark unbecoming of a teacher." },
  { t: "〜ずくめ", n: "all… through and through", e: "One colour over everything: 黒ずくめ, いいことずくめ.", ex: "今日は いいことずくめだ。", en: "Today's been good news through and through." },
  { t: "〜まみれ", n: "smeared with", e: "Coated in the stuff: 汗まみれ, 泥まみれ.", ex: "汗まみれで 働いた。", en: "(He) worked drenched in sweat." },
  { t: "〜がてら", n: "while at it", e: "One outing, two purposes.", ex: "散歩がてら 買い物に 行く。", en: "(I'll) shop while out for a walk." },
  { t: "〜かたがた", n: "partly to (formal)", e: "The formal two-birds visit.", ex: "お礼かたがた うかがいます。", en: "(I'll) visit, partly to thank you." },
  { t: "〜かたわら", n: "alongside (a life)", e: "The main life, with another pursuit beside it.", ex: "仕事の かたわら 小説を 書く。", en: "Alongside work, (she) writes novels." },
  { t: "〜そばから", n: "no sooner than", e: "Undone the moment it's done, again and again.", ex: "覚えるそばから 忘れる。", en: "(I) forget things the moment (I) learn them." },
  { t: "〜が早いか", n: "the second that", e: "B was already moving when A finished.", ex: "ベルが 鳴るが早いか、走り出した。", en: "The second the bell rang, (they) bolted." },
  { t: "〜や否や", n: "no sooner had", e: "The literary “the instant”.", ex: "着くや否や、会議が 始まった。", en: "No sooner had (I) arrived than the meeting began." },
  { t: "〜なり", n: "the moment (and then…)", e: "Right on A's heels came surprising B.", ex: "顔を 見るなり、泣き出した。", en: "The moment (she) saw his face, (she) burst into tears." },
  { t: "〜なりに", n: "in one's own way", e: "Within those limits, a real effort.", ex: "子どもなりに 考えた。", en: "The child thought it through in his own way." },
  { t: "〜きらいがある", n: "has a bad habit of", e: "A tendency, frowned at.", ex: "物事を 悪く 考えるきらいが ある。", en: "(He) tends to see things darkly." },
  { t: "〜極まりない", n: "beyond measure", e: "The formal “utterly”: 失礼極まりない.", ex: "危険極まりない 運転だ。", en: "Driving dangerous beyond measure." },
  { t: "〜の極み", n: "the height of", e: "The very peak: 感激の極み.", ex: "ぜいたくの 極みだ。", en: "The height of luxury." },
  { t: "〜の至り", n: "the utmost of (humble)", e: "Ceremonial gratitude or shame: 光栄の至り.", ex: "若気の 至りだった。", en: "It was youthful folly." },
  { t: "〜に堪えない", n: "unbearable to / deeply", e: "Too much to watch or hear — or feeling past words.", ex: "見るに 堪えない。", en: "Unbearable to watch." },
  { t: "〜に足る", n: "worthy of", e: "Measures up to it: 信頼に足る.", ex: "尊敬に 足る 人物だ。", en: "A person worthy of respect." },
  { t: "〜にかたくない", n: "easy to (imagine)", e: "No effort needed: 想像にかたくない.", ex: "苦労は 想像に かたくない。", en: "The hardship is easy to imagine." },
  { t: "〜を余儀なくされる", n: "forced into", e: "Circumstances left no other road.", ex: "中止を 余儀なくされた。", en: "(They) were forced to cancel." },
  { t: "〜を禁じ得ない", n: "can't hold back", e: "The feeling breaks through: 涙を禁じ得ない.", ex: "怒りを 禁じ得ない。", en: "(I) can't hold back (my) anger." },
  { t: "〜をおいて", n: "no one but", e: "The only candidate there is.", ex: "彼を おいて 適任者は いない。", en: "There's no one for it but him." },
  { t: "〜をもって", n: "with / as of", e: "The formal instrument or cut-off: 本日をもって.", ex: "本日を もって 閉店します。", en: "As of today, (we) close." },
  { t: "〜はおろか", n: "let alone", e: "Even the small thing fails — never mind the big one.", ex: "漢字は おろか、ひらがなも 書けない。", en: "(He) can't write hiragana, let alone kanji." },
  { t: "〜ならでは", n: "only possible from", e: "The flavour nothing else could give: 京都ならでは.", ex: "手作りならではの 味だ。", en: "A taste only homemade has." },
  { t: "〜ですら", n: "even (emphatic)", e: "The heavy “even”: 専門家ですら.", ex: "先生ですら 間違える。", en: "Even teachers slip." },
  { t: "〜だに", n: "even just (to think)", e: "The mere act is too much: 想像するだに.", ex: "思い出すだに 恐ろしい。", en: "Frightening even to recall." },
  { t: "〜たりとも", n: "not even one", e: "Zero exceptions: 一日たりとも.", ex: "一円たりとも むだに しない。", en: "Not one yen goes to waste." },
  { t: "〜といえども", n: "even granting", e: "The stately “even though”.", ex: "王といえども、法には 従う。", en: "Even a king obeys the law." },
  { t: "〜ときたら", n: "when it comes to (exasperated)", e: "Names the offender, rolls its eyes.", ex: "うちの 犬ときたら、寝てばかりだ。", en: "That dog of ours — all it does is sleep." },
  { t: "〜とあって", n: "given the occasion", e: "Special circumstances, matching behaviour.", ex: "祭りとあって、町は にぎやかだ。", en: "With the festival on, the town is buzzing." },
  { t: "〜とあれば", n: "if it's for", e: "For that, anything.", ex: "君の 頼みとあれば、断れない。", en: "If it's your request, (I) can't refuse." },
  { t: "〜にあって", n: "in (such a place/time)", e: "Set inside those circumstances.", ex: "非常時に あって、冷静だった。", en: "In the emergency, (she) stayed calm." },
  { t: "〜にして", n: "only at / even for", e: "Only at that level — or “in one stroke”: 一瞬にして.", ex: "五十歳に して 初めて 海を 見た。", en: "Only at fifty did (he) first see the sea." },
  { t: "〜であれ", n: "be it", e: "Whichever it is, the claim stands: 誰であれ.", ex: "理由が 何であれ、暴力は だめだ。", en: "Whatever the reason, violence is out." },
  { t: "〜つ〜つ", n: "back and forth", e: "Two doings trading places: 行きつ戻りつ.", ex: "浮きつ沈みつ 流れていく。", en: "Bobbing up and down, it drifts away." },
  { t: "〜ばこそ", n: "precisely because (formal)", e: "The old-style からこそ.", ex: "愛すればこそ、叱る。", en: "(I) scold precisely because (I) care." },
  { t: "〜といったらない", n: "beyond words", e: "The degree defies description.", ex: "うれしいといったらない。", en: "Happy beyond words." },
  { t: "〜限りだ", n: "utterly (feeling)", e: "Your feeling at full volume: うらやましい限りだ.", ex: "心細い 限りだ。", en: "(I) feel utterly forlorn." },
  { t: "〜ずじまい", n: "ended up never", e: "The chance closed with it undone.", ex: "会えずじまいだった。", en: "(We) ended up never meeting." },
  { t: "〜放題", n: "as much as you like", e: "No limits: 食べ放題.", ex: "ここは 飲み放題だ。", en: "Drinks here are all-you-can-drink." },
  { t: "〜まくる", n: "do like crazy", e: "The doing, flat out: 買いまくる.", ex: "一晩中 歌いまくった。", en: "(We) sang our heads off all night." },
  { t: "〜こととて", n: "it being (excuse)", e: "The old-style apologetic “because”.", ex: "急な こととて、準備が ない。", en: "It being so sudden, nothing is ready." },
  { t: "〜ゆえに", n: "therefore (literary)", e: "The classical “because / thus”.", ex: "若さゆえの 過ちだ。", en: "A mistake born of youth." },
  { t: "〜なくして（は）", n: "without (there's nothing)", e: "Take it away and the rest collapses.", ex: "努力なくして 成功は ない。", en: "No success without effort." },
  { t: "〜ならまだしも", n: "if it were only", e: "That much could pass — this can't.", ex: "一度なら まだしも、三度目だ。", en: "Once might pass — this is the third time." },
  { t: "〜たるもの", n: "one who stands as", e: "The duty that comes with the title.", ex: "教師たるもの、公平であれ。", en: "A teacher, as such, must be fair." },
  { t: "〜ともなると", n: "once you're at (that level)", e: "At that stage, things change accordingly.", ex: "プロともなると、練習量が ちがう。", en: "Once you're a pro, the training is another world." },
];
